version: '3.8'

services:
  semantic-threat-analysis:
    build: .
    container_name: semantic-threat-analysis
    environment:
      - OPENCTI_API_URL=http://opencti:8080
      - OPENCTI_API_TOKEN=changeme
    ports:
      - "5000:5000"
    depends_on:
      - opencti
    volumes:
      - ./:/app
    restart: unless-stopped

  opencti:
    image: opencti/platform:latest
    environment:
      - APP__ADMIN__EMAIL=admin@localhost
      - APP__ADMIN__PASSWORD=changeme
    ports:
      - "8080:8080"
    restart: unless-stopped