# Configuration file for AI-driven Semantic Framework

# Data settings
data:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  sample_size: 1000

# Model settings
models:
  ml_model:
    type: "random_forest"  # Options: random_forest, svm, gradient_boosting, naive_bayes
    n_estimators: 100
    max_depth: 10
    
  dl_model:
    type: "lstm"  # Options: lstm, cnn
    vocab_size: 10000
    embedding_dim: 128
    max_length: 100
    epochs: 50
    batch_size: 32

# Semantic analysis settings
semantic:
  max_features: 5000
  ngram_range: [1, 3]
  similarity_threshold: 0.7

# Real-time detection settings
realtime:
  queue_size: 1000
  processing_threads: 4
  alert_threshold: 0.7

# API settings
api:
  host: "0.0.0.0"
  port: 5000
  debug: false
  cors_enabled: true

# Logging settings
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "logs/framework.log"
